# Generated by Django 4.2.3 on 2023-08-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('TVSERIES', 'TV Series'), ('WEBSERIES', 'Web Series')], default='MOVIE', max_length=30),
        ),
    ]
