# Generated by Django 4.2.3 on 2023-08-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_movie_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='subcategory',
            new_name='subcategories',
        ),
    ]
