# Generated by Django 4.2.4 on 2023-09-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_link',
            field=models.URLField(),
        ),
    ]
