# Generated by Django 4.2.4 on 2023-09-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_link',
        ),
    ]
