# Generated by Django 4.2.4 on 2023-09-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_movie_video_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
