# Generated by Django 4.2.5 on 2023-09-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='iframe_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
