# Generated by Django 4.2.5 on 2023-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_movie_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pages',
            field=models.IntegerField(default=1),
        ),
    ]
