# Generated by Django 4.2.5 on 2023-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_movie_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
