# Generated by Django 4.2.5 on 2023-09-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movie_movie_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='pages',
        ),
    ]
