# Generated by Django 4.2.5 on 2023-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_alter_moviepart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepart',
            name='iframe_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
