# Generated by Django 4.2.5 on 2023-09-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_episode_delete_moviepart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
