# Generated by Django 4.2.5 on 2023-09-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_episode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
