# Generated by Django 4.2.5 on 2023-09-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_series_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='series',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
        migrations.AddField(
            model_name='episode',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
