# Generated by Django 4.2.5 on 2023-09-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_remove_episode_episode_number_remove_episode_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
