# Generated by Django 4.2.5 on 2023-09-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_alter_episode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
