# Generated by Django 4.2.5 on 2023-09-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_movie_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
