# Generated by Django 4.2.5 on 2023-09-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_alter_movie_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fasl',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='qism',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
