# Generated by Django 4.2.5 on 2023-09-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0044_alter_movie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_premiere',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
