# Generated by Django 4.2.5 on 2023-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0045_movie_is_premiere_delete_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_premiere',
            field=models.BooleanField(default='Yangi'),
        ),
    ]
