# Generated by Django 4.2.5 on 2023-09-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0048_alter_movie_is_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_premiere',
            field=models.BooleanField(default=True),
        ),
    ]
