# Generated by Django 4.2.5 on 2023-09-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0053_remove_review_likes_movie_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
    ]
