# Generated by Django 4.2.5 on 2023-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0055_remove_movie_homiy_remove_movie_yoshcheklovi'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='homiy',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='yoshcheklovi',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
